FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY target/*.jar app.jar
COPY src/main/resources/static ./static
COPY src/main/resources/application.yml ./config/application.yml
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
