server:
  port: 8080

spring:
  application:
    name: api-gateway
  web:
    resources:
      static-locations: classpath:/static/
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s
        wiretap: true
      httpserver:
        wiretap: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

jwt:
  secret: ${JWT_SECRET:c2VjcmV0LWtleS1jYWtlLWRlbGlnaHQtdjItc3VwZXItc2VjcmV0LXNlY3JldC1rZXk=}

gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET:c2VjcmV0LWtleS1jYWtlLWRlbGlnaHQtdjItc3VwZXItc2VjcmV0LXNlY3JldC1rZXk=}

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG



