server:
  port: 8080

spring:
  application:
    name: api-gateway
  web:
    resources:
      static-locations: classpath:/static/
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

