apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cake-delight
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql.yaml
  - rabbitmq.yaml
  - mailhog.yaml
  - catalog-service.yaml
  - order-service.yaml
  - rating-service.yaml
  - notification-service.yaml
  - api-gateway.yaml
