apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-config
  namespace: cake-delight
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS cake_catalog;
    CREATE DATABASE IF NOT EXISTS cake_order;
    CREATE DATABASE IF NOT EXISTS cake_rating;
    CREATE DATABASE IF NOT EXISTS notification_db;
    CREATE DATABASE IF NOT EXISTS user_db;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: cake-delight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cake-delight
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cake-delight-secrets
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
              subPath: data
            - name: mysql-init-script
              mountPath: /docker-entrypoint-initdb.d
          startupProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-init-script
          configMap:
            name: mysql-init-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cake-delight
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
