apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: cake-delight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: cake-delight-notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 10
          env:
            - name: SERVER_PORT
              value: "8084"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/notification_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cake-delight-secrets
                  key: MYSQL_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cake-delight-secrets
                  key: MYSQL_PASSWORD
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cake-delight-secrets
                  key: RABBITMQ_PASSWORD
            - name: SPRING_MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: SPRING_MAIL_HOST
            - name: SPRING_MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: SPRING_MAIL_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: cake-delight
spec:
  selector:
    app: notification-service
  ports:
    - port: 8084
      targetPort: 8084
