apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: cake-delight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: cake-delight-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SERVER_PORT
              value: "8082"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/cake_order?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cake-delight-secrets
                  key: MYSQL_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cake-delight-secrets
                  key: MYSQL_PASSWORD
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: RABBITMQ_HOST
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: RABBITMQ_PORT
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: cake-delight-config
                  key: RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cake-delight-secrets
                  key: RABBITMQ_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: cake-delight
spec:
  selector:
    app: order-service
  ports:
    - port: 8082
      targetPort: 8082
