apiVersion: v1
kind: Secret
metadata:
  name: cake-delight-secrets
  namespace: cake-delight
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: Sweetlife&15
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: Sweetlife&15
  RABBITMQ_PASSWORD: guest
  SPRING_MAIL_USERNAME: ""
  SPRING_MAIL_PASSWORD: ""
